spring.application.name=taskmanager
server.port=8081

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ethara_ai
spring.datasource.username=root
spring.datasource.password=0000

# JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Configuration (Custom)
ethara.app.jwtSecret=TaskManagementAppSecretKeyForJWTAuthTokenGenerationMustBeLongEnough
ethara.app.jwtExpirationMs=86400000

# Logging
logging.level.org.springframework.security=DEBUG
